hash-format = "sha256"

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "95322b6e88dbeba91b5e7a30d6bd011629124ae8aef5bf1b7d1304f12bd4619c"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "9bef0951501cb99b09b958f28efb5eacfbc6376ed8a6b108ea3b56cd7ace0bd5"
metafile = true

[[files]]
file = "mods/cobblemon-pokemon-badges.pw.toml"
hash = "1f2cd45c3decc1215fca84fb3df356d017f17dbd130f18704fea55772a140adf"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "626d8158ec0e84758abfb66ad1ae4e53f353f995bda5ae52b2b0b662f3420248"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/more-radical-trainers.pw.toml"
hash = "29673e522060c530979217c750adf7723ed009eda5fe013cd6bc7a52eacda700"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/parcool.pw.toml"
hash = "0dc8617f17a7d980064f78a2c1735af15f912989fb03bf8c46470c3dcb74cb86"
metafile = true

[[files]]
file = "mods/rctapi.pw.toml"
hash = "f7d08345088ecc388773f5411370ea595728ec3c97a88d87fed7a078ad3ce711"
metafile = true

[[files]]
file = "mods/rctmod.pw.toml"
hash = "baf0cd242ee5caf961e8281ca9ef4e0a60e0a2acdcdcfd00d8f5766ae8f2d54a"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "307a39080394cbe930be57e67fb8dae37601e8f0842da10da10977d261dac07d"
metafile = true

[[files]]
file = "mods/tutorial-suppressor.pw.toml"
hash = "86c677f1adb41d282bdad04c70fec57855a6c39b00ce70c1390477c01e788dc1"
metafile = true

[[files]]
file = "resourcepacks/rct-trainer-animation.pw.toml"
hash = "2a88fb3736a1e282b0f5d92bcdd9d16e0d79e27e563efa9e7dfe7c14e91344f9"
metafile = true

[[files]]
file = "resourcepacks/rct-trainer-textures-plus.pw.toml"
hash = "a958030f95997d32191ffd80d656314b86747c46adfb16a3a128389d6a3ff6c9"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
hash = "32fe0fe8941110f8fba07ce7768faa1797de6b28e961ab65b483c380fc0a365a"
metafile = true
