name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6727c0c1d16b0f3cf81cbad3fb8d7c0e8b3bbf4a62dc77ba1fbb03ccdc1376d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
