name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "552be86f72e48b731d0e090632f3a38d7b255cfe20b8fe28581f040618d15479"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
datapack-folder = "global_packs/required_data/"
