name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa5d4b2b1ce7adbf5a310ac335b8d2e06736141f7813558a11076266376a7e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
