name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "361373e09b0ee769b277d25c33754ee646703492cbcffffe7c09f0c8ac16feb4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
