name = "CobbleQuest"
author = "Arimil"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6a35cea36d0b4656ef31c4e78e24529926c96fc0821932ed4dce0edc6ba7a98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
