name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "228efcef708614add34ec6cd5fcd8f499170111c3c5d75b47d09d306e0c3530b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
