name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98713c5e90f57593c87cc8ad03fdcd02b8926e3725f99bbdc6377d88cf276ec6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
