name = "CobbleQuest"
author = "Arimil"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6b23dbd164799b992771c799730006514ab52f5202c53a76426f501f4ac2d14"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
