name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bb956d57a29c572f28de9131fdda6a92f85f5d86e125b16b6b4be4468ff117a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
datapack-folder = "global_packs/required_data/"
