name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97412ab5e4f0f3a8d5545ff52068241125ceb0cc3cdf7c3f9cfb8fc830d096ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
