name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b8b2b77dd5d89a69d6aa51537df0b196710f8264e3612f3323a00c7e16aa6f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
datapack-folder = "global_packs/required_data/"
