name = "CobbleQuest"
author = "Arimil"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2999e623abbc0bcebb09fed08e4ad0ed82e847412601dd37e487680f306e606a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
