name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cb7643d74b7942e0d33cbcd382df60e892e71c6d62d684217bba1afa95f4ac2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
