name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c93fc9f9004bac1987330be5ecdde43285b028eedc1fdc3ef475040249697648"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
