name = "CobbleQuest"
author = "Arimil"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a95171e438356d73d82e63702786d01e760154749c73aec9eb16b7f64d691419"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
